version: "3"
services:
  extractor:
    build: extractor
    volumes:
      - papers:/papers
  sciscore:
    build: sciscore
    volumes:
      - papers:/papers
    env_file:
      - auth.env
  limitation-recognizer:
    build: limitation-recognizer
    volumes:
      - papers:/papers
  oddpub:
    build: oddpub
    volumes:
      - papers:/papers
  release:
    build: release
    volumes:
      - papers:/papers
      - ./performance-data:/performance-data
    networks:
      - db-net
    env_file:
      - auth.env
  barzooka:
    build: barzooka
    volumes:
      - papers:/papers
  trial-identifier:
    build: trial-identifier
    volumes:
      - papers:/papers
  jetfighter:
    build: jetfighter
    volumes:
      - papers:/papers
  find-new:
    build: find-new
    volumes:
      - papers:/papers
    networks:
      - db-net
    env_file:
      - auth.env
  annotation-db:
    image: postgres
    container_name: annotation-db
    networks:
      - db-net
    environment:
      - POSTGRES_PASSWORD=gxDqwldOtdbbb7BP
    ports:
      - 5432:5432
    volumes:
      - ./annotation-db:/var/lib/postgresql/data

volumes:
  papers:
  annotation-db:
  performance-data:

networks:
  db-net: