version: "3"
services:
  database:
    image: postgres:12
    container_name: database
    env_file:
      - auth.env
    networks:
      - database-network
    ports:
      - 5434:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  pipeline:
    build: .
    env_file:
      - auth.env
    networks:
      - database-network
    ports:
      - "8000:8000"

volumes:
  database:

networks:
  database-network:
