create table preprints (
id integer primary key generated always as identity,
doi text unique,
has_full_text_html boolean,
report_exists boolean,
report_already_existed boolean,
release_status integer,
annotation_link text,
report_generated timestamp with time zone,
url text,
title text,
abstract text,
authors json,
publication_date date,
html_report text,
tweet_text text,
discussion_text text,
methods_text text,
all_text text,
jet_page_numbers json,
limitation_sentences json,
trial_numbers json,
sciscore json,
is_modeling_paper boolean,
graph_types json,
is_open_data boolean,
is_open_code boolean
)